
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: contract-zs
      url: jdbc:mysql://rm-2ze26op6tgff5p2xaoo.mysql.rds.aliyuncs.com:3306/lyq?characterEncoding=utf-8
      username: zhy
      password: Zhy980721
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        config:
          enabled: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# 钉钉配置信息
dd-config:
  domainname: openplatform.dg-work.cn
  pc:
    key: jcxq-B6xnw6e84El5T9kHRgLANfQFj
    secret: B4N7HZ854r5YipLrL5xo4H27B2Zd3a9D526VTjCz
    appId:
    tenantId: "42329"
  qrcode:
    key:
    secret:
  phone:
    key: jcxq_phone-a1Ux22q58uh47EVzmym
    secret: klF6he2080cDV9oNXMnLlklCIVov3HB007xlfUfH
    appId: "0211103143749848"
    tenantId: "42329"
