
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: contract-zs
      url: jdbc:mysql:///contract-tl?characterEncoding=utf-8
      #      url: jdbc:mysql://zenghy.top:3306/contract-tl?characterEncoding=utf-8
      username: root
      password: TLjcxq@rootpwd
      #      password: 123456
      #password: PeZXs33C7QxuHeCqFkrnE0LZDqL4Va5rmA2PyzFvD6d5YpRzqT/K5EMt2Cl6aPU2YGQ0ml873ERm+xmyqC2s2g==
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: tladmin
        login-password: tl.8520
      filter:
        config:
          enabled: true
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

# 钉钉配置信息
dd-config:
  domainname: openplatform-pro.ding.zj.gov.cn
  pc:
    key: tljcxq-28482CzWzS02D3C42UzmaYz
    secret: deY89DGs82zKX90H8i69B8OWgeo0RX7V1fyeoX4b
    appId:
    tenantId: "196729"
  qrcode:
    key: tljcxq_dingoa-GgydR7VabgRZz67f
    secret: C3g2KiJo4gCNTzr93V0l01s7xDM4Fv0dgsfYkN27
  phone:
    key: tlzsjc-bQiLs70gGyreSNBr1MNNbAb
    secret: 2k8ic6o5W08hWgXDsKx0DxoFmWoHM1P8fVV0W5ih
    appId: "0211230104836714"
    tenantId: "196729"
